### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_annotations' 

### ISSUE THREAD

**Issue by Markzhiyuan** [marcocor/tagme-python#10]
When I run the example codes I get this error, other codes get the same error.  The python version I used is 3.6.

**Comment by Markzhiyuan** [comment]
WARNING:root:Tagme returned status code 500 message:
b'Error (500) : unexpected error\nStacktrace:\norg.gcube.smartgears.handlers.application.request.RequestException: error contacting authorization service\n\tat org.gcube.smartgears.handlers.application.request.RequestError.toException(RequestError.java:110)\n\tat org.gcube.smartgears.handlers.application.request.RequestError.fire(RequestError.java:94)\n\tat org.gcube.smartgears.handlers.application.request.RequestContextRetriever.retreiveAndSetInfo(RequestContextRetriever.java:80)\n\tat org.gcube.smartgears.handlers.application.request.RequestContextRetriever.handleRequest(RequestContextRetriever.java:56)\n\tat org.gcube.smartgears.handlers.application.RequestHandler.onEvent(RequestHandler.java:58)\n\tat org.gcube.smartgears.handlers.application.RequestHandler.onEvent(RequestHandler.java:21)\n\tat org.gcube.smartgears.handlers.Pipeline.forward(Pipeline.java:65)\n\tat org.gcube.smartgears.managers.RequestManager.doFilter(RequestManager.java:86)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)\n\tat it.acubelab.tagme.web.SetCharEncodingValve.invoke(SetCharEncodingValve.java:18)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)\n\tat org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)\n\tat org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:683)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)\n\tat org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)\n\tat org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)\n\tat org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n'

**Comment by Markzhiyuan** [comment]
I find the error is that I add unnecessary <> with the token.

**Comment by thetaaaaa** [comment]
Hi, I got the same error when I run the example codes, and I have no '<>' in my code except `tagme.GCUBE_TOKEN = "<Your token goes here>"`, could please show me your example code which has been successfully running?
