### ISSUE TITLE
Unable to obtain auth. token

### ISSUE THREAD

**Issue by vardaan123** [marcocor/tagme-python#11]
Hi, when I clicked on the link given in the README and I signed in, I get the error message "You do not have permission to access the requested resource. https://services.d4science.org/group/tagme/".

Is there any specific VRE should I register for to obtain the auth. token? I tried to register in AnalyticsLab VRE but I get the error
```
Error (400) : this resource cannot process this request because it is malformed\nStacktrace:\norg.gcube.smartgears.handlers.application.request.RequestException: TagMe cannot be called in scope /d4science.research-infrastructures.eu/D4Research/AnalyticsLab
```

**Comment by marcocor** [comment]
Hi Vardaan,

It seems that you did create an account (if you didn't, [create one here](https://sobigdata.d4science.org/home?p_p_id=58&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=2&saveLastPath=false&_58_struts_action=%2Flogin%2Fcreate_account)) but don't have access to the Tagme VRE. You can get access [here](https://services.d4science.org/group/sobigdata-gateway/explore?siteId=22994).

**Comment by vardaan123** [comment]
When I click on the given link (here), I get an error (see attached screenshot)
<img width="984" alt="Screen Shot 2020-10-18 at 12 27 17 PM" src="https://user-images.githubusercontent.com/17354381/96373924-87907280-113d-11eb-9003-505cd16b3d22.png">

**Comment by vardaan123** [comment]
I created a new account (instead of using my Gmail) and it works now. Thanks
