### ISSUE TITLE
Retrieving QID after getting annotations

### ISSUE THREAD

**Issue by belizgunel** [marcocor/tagme-python#4]
Hi,

Thanks for open-sourcing this, it's a great resource!

I had a question about retrieving QIDs for the Wikidata entities. It's easy to get the entity titles, but I realized entity_id doesn't correspond to QIDs. Is there a way to retrieve QIDs after getting the annotations?

Thanks,
Beliz

**Comment by leonardmq** [comment]
You can retrieve the Wikidata IDs using the Wikipedia API. You could do something along these lines:

```python
import requests

def enwiki_title_to_wikidata_id(title: str) -> str:
        protocol = 'https'
        base_url = 'en.wikipedia.org/w/api.php'
        params = f'action=query&prop=pageprops&format=json&titles={title}'
        url = f'{protocol}://{base_url}?{params}'
        
        response = requests.get(url)
        json = response.json()
        for pages in json['query']['pages'].values():
            wikidata_id = pages['pageprops']['wikibase_item']
        return wikidata_id
```
