### ISSUE TITLE
not able to find the authorization token in https://services.d4science.org/home

### ISSUE THREAD

**Issue by Ravikiran2611** [marcocor/tagme-python#5]
hi 
i created an account the  link https://services.d4science.org/home , but i could no tfind the show button to get the authorization token 
can anyone help me how to proceed 
Thanks in advance !!!!!!!!!!!!!!!!!!!!

**Comment by yukunfeng** [comment]
Hi, perhaps you've solved this. I also took some time to figure it out about the token. Just posted it here for other people. First register at d4science and then enter tagme VRE (https://services.d4science.org/group/d4science-services-gateway/explore?siteId=22994), you can see the show button there.
