### ISSUE TITLE
Setting parameters in the annotate function

### ISSUE THREAD

**Issue by chsuong** [marcocor/tagme-python#8]
Thanks so much for this wrapper! 

I'm trying to set some parameters for the annotate function. The tagme documentation [https://sobigdata.d4science.org/web/tagme/tagme-help] says users can enable the options "include_abstract" and "include_categories." But when I include these options, I get the error "TypeError: annotate() got an unexpected keyword argument 'include_categories" as the following: 

![image](https://user-images.githubusercontent.com/8497341/69659861-18092480-104d-11ea-83c2-11d2bb05e48a.png)

**Comment by marcocor** [comment]
Hi @chsuong ,
unfortunately this wrapper only provides the basic annotation functionalities. If you want to issue advanced parameters, you'll have to query the API directly.
