### ISSUE TITLE
The reuturn of any tagme api is Nonetype

### ISSUE THREAD

**Issue by liyushihaoren2** [marcocor/tagme-python#9]

**Comment by zahramahani** [comment]
hi i want to work with this for other languages and the return result is null 
did you find any answer or way to solve this ?
@liyushihaoren2 
@marcocor 

with respect

**Comment by marcocor** [comment]
Hi @zahramahani ,

This is just a wrapper around the TagME web service. Currently only three languages are supported: German, Italian and English. Fore info here:

https://sobigdata.d4science.org/group/tagme/tagme-help
